version: '3.8'

services:
  web_dev:
    build: 
      context: ./app
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db_dev
  db_dev:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=next_django
      - POSTGRES_PASSWORD=next_django
      - POSTGRES_DB=next_django_dev


volumes:
  postgres_data_dev:
